# Collector specific configuration
url: "https://helix-tools-api.idmcdb.org/external-api/idus/last-180-days/"
hxltags:
  "country": "#country+name"
  "iso3": "#country+iso3"
  "latitude": "geo+lat"
  "longitude": "geo+lon"
  "displacement_type": "#event+displacement_type"
  "qualifier": "total"
  "figure": "#affected+displaced"
  "displacement_date": "#date+displacement"
  "displacement_start_date": "#date+displacement+start"
  "displacement_end_date": "#date+displacement+end"
  "year": "#date+year"
  "event_name": "#event+name"
  "event_start_date": "#date+event+start"
  "event_end_date": "#date+event+end"
  "type": "#event+type"
  "subtype": "#event+subtype"
  "created_at": "#date+created"
  "description": "#description"
  "link": "#meta+url"
  "combined_type": "#cause"
description: Internally displaced persons are defined according to the 1998 Guiding Principles (http://www.internal-displacement.org/publications/1998/ocha-guiding-principles-on-internal-displacement) as people or groups of people who have been forced or obliged to flee or to leave their homes or places of habitual residence, in particular as a result of armed conflict, or to avoid the effects of armed conflict, situations of generalized violence, violations of human rights, or natural or human-made disasters and who have not crossed an international border.