# Collector specific configuration
url: "https://helix-tools-api.idmcdb.org/external-api/idus/last-180-days/"
hxltags:
  "country": "#country+name"
  "iso3": "#country+iso3"
  "latitude": "geo+lat"
  "longitude": "geo+lon"
  "displacement_type": "#cause"
  "qualifier": "total"
  "figure": "#affected+displaced"
  "displacement_date": "#date+displacement"
  "displacement_start_date": "#date+displacement+start"
  "displacement_end_date": "#date+displacement+end"
  "year": "#date+year"
  "event_name": "#event+name"
  "event_start_date": "#date+event+start"
  "event_end_date": "#date+event+end"
  "type": "#event+supertype"
  "subtype": "#event+type"
  "created_at": "#date+created"
  "description": "#description"
  "link": "#meta+url"